# Generated by Django 5.2.11 on 2026-02-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(blank=True, max_length=255, verbose_name='Domaine du site'),
        ),
    ]
