# Generated by Django 5.2.11 on 2026-04-18 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0006_site_vercel_deploy_hook'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='Utilisée pour accéder aux articles depuis le frontend du site', max_length=64, verbose_name='Clé API publique'),
        ),
        migrations.AlterField(
            model_name='site',
            name='database_url',
            field=models.TextField(blank=True, default='', help_text='Laisser vide pour utiliser le stockage hébergé du dashboard', verbose_name='DATABASE_URL PostgreSQL'),
        ),
        migrations.CreateModel(
            name='HostedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_categories', to='sites_mgmt.site')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('site', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='HostedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_tags', to='sites_mgmt.site')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('site', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HostedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('cover_image', models.URLField(blank=True, max_length=500)),
                ('reading_time', models.PositiveIntegerField(default=5)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie'), ('scheduled', 'Planifie')], default='published', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='sites_mgmt.hostedcategory')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_posts', to='sites_mgmt.site')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='sites_mgmt.hostedtag')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['site', '-published_at'], name='sites_mgmt__site_id_992943_idx'), models.Index(fields=['site', 'slug'], name='sites_mgmt__site_id_f3d1b6_idx')],
                'unique_together': {('site', 'slug')},
            },
        ),
    ]
