# Generated by Django 5.2.11 on 2026-04-18 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0007_site_api_key_alter_site_database_url_hostedcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedpost',
            name='language',
            field=models.CharField(choices=[('fr', 'Francais'), ('en', 'English'), ('es', 'Espanol')], db_index=True, default='fr', max_length=2),
        ),
        migrations.AddField(
            model_name='hostedpost',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
