# Generated by Django 5.2.13 on 2026-04-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0008_hostedpost_language_hostedpost_translation_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='gsc_property_url',
            field=models.URLField(blank=True, default='', help_text='URL de la propriété Search Console (ex: https://tokamdarius.ca/)', max_length=300),
        ),
        migrations.AddField(
            model_name='site',
            name='gsc_refresh_token',
            field=models.TextField(blank=True, default='', help_text='OAuth2 refresh token chiffré'),
        ),
    ]
