# Generated by Django 5.2.13 on 2026-04-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0009_site_gsc_property_url_site_gsc_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='available_languages',
            field=models.JSONField(blank=True, default=None, help_text="Liste de codes ISO acceptés par le site (ex: ['fr','en']). Null = toutes (fr/en/es).", null=True, verbose_name='Langues disponibles'),
        ),
    ]
