# Generated by Django 5.0.6 on 2026-04-27 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0010_site_available_languages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='default_author',
            field=models.CharField(blank=True, default='', help_text="Nom d'auteur attribué aux articles générés (utilisé aussi pour Schema.org). Vide = 'Admin'.", max_length=100, verbose_name='Auteur par défaut'),
        ),
        migrations.AddField(
            model_name='site',
            name='default_language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español')], default='fr', help_text="Langue présélectionnée dans l'éditeur et la génération IA", max_length=2, verbose_name='Langue par défaut'),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Courte description (utilisée pour Open Graph / about-page)', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Décoche pour suspendre le site (lectures bloquées, génération désactivée)', verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='site',
            name='og_image_url',
            field=models.URLField(blank=True, default='', help_text="URL de l'image utilisée comme fallback Open Graph quand un article n'a pas de cover", max_length=500, verbose_name='Image OG par défaut'),
        ),
        migrations.AddField(
            model_name='site',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='api_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Utilisée comme header X-Api-Key pour les endpoints publics. Auto-générée.', max_length=64, verbose_name='Clé API publique'),
        ),
        migrations.AlterField(
            model_name='site',
            name='available_languages',
            field=models.JSONField(blank=True, default=list, help_text="Liste de codes ISO acceptés (ex: ['fr','en']). Vide = toutes (fr/en/es).", verbose_name='Langues disponibles'),
        ),
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(blank=True, db_index=True, help_text='Sans https:// ni slash final (ex: tokamdarius.ca)', max_length=255, verbose_name='Domaine du site'),
        ),
        migrations.AlterField(
            model_name='site',
            name='gsc_property_url',
            field=models.URLField(blank=True, default='', help_text='URL de la propriété Search Console (ex: https://tokamdarius.ca/)', max_length=300, verbose_name='Search Console — URL propriété'),
        ),
        migrations.AlterField(
            model_name='site',
            name='gsc_refresh_token',
            field=models.TextField(blank=True, default='', help_text='OAuth2 refresh token (sensible — ne pas exposer côté frontend)', verbose_name='Search Console — refresh token'),
        ),
        migrations.AlterField(
            model_name='site',
            name='knowledge_base',
            field=models.TextField(blank=True, default='', help_text="Contexte personnel pour la génération d'articles (qui tu es, tes projets, ton ton, etc.)", verbose_name='Base de connaissances'),
        ),
        migrations.AlterField(
            model_name='site',
            name='vercel_deploy_hook',
            field=models.URLField(blank=True, default='', help_text="URL du Deploy Hook pour redéployer Vercel après chaque modification d'article", max_length=500, verbose_name='Vercel Deploy Hook'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['owner', 'is_active'], name='sites_mgmt__owner_i_fb8162_idx'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_site_owner_name'),
        ),
    ]
