# Generated by Django 5.0.6 on 2026-05-05 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0011_site_default_author_site_default_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español')], default='fr', max_length=2)),
                ('target_url', models.URLField(blank=True, default='', help_text='Optional. The article URL we expect to rank — used to highlight if the page actually ranks.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_keywords', to='sites_mgmt.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SerpRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='Position 1-100, NULL if not in top 100', null=True)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('is_target_match', models.BooleanField(default=False, help_text='True if the ranking URL matches the tracked target_url')),
                ('source', models.CharField(default='serper', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tracked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='sites_mgmt.trackedkeyword')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trackedkeyword',
            index=models.Index(fields=['site', 'is_active'], name='sites_mgmt__site_id_9a3229_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trackedkeyword',
            unique_together={('site', 'keyword', 'language')},
        ),
        migrations.AddIndex(
            model_name='serprank',
            index=models.Index(fields=['tracked', '-recorded_at'], name='sites_mgmt__tracked_44d9a2_idx'),
        ),
    ]
