# Generated by Django 5.0.6 on 2026-05-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0013_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='author_bio',
            field=models.TextField(blank=True, default='', help_text="2-4 phrases qui établissent l'expertise (E-E-A-T : experience, expertise, authority, trust)", verbose_name="Bio de l'auteur"),
        ),
        migrations.AddField(
            model_name='site',
            name='author_credentials',
            field=models.TextField(blank=True, default='', help_text='Diplômes, certifications, expérience pertinente. Visible publiquement et utilisé en JSON-LD.', verbose_name='Crédentials / qualifications'),
        ),
        migrations.AddField(
            model_name='site',
            name='author_image_url',
            field=models.URLField(blank=True, default='', help_text="URL d'une photo professionnelle (JSON-LD Person.image)", max_length=500, verbose_name="Photo de l'auteur"),
        ),
        migrations.AddField(
            model_name='site',
            name='author_linkedin',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='site',
            name='author_role',
            field=models.CharField(blank=True, default='', help_text='Ex: Fondateur, Consultant SEO, Avocat fiscaliste', max_length=200, verbose_name="Rôle / titre de l'auteur"),
        ),
        migrations.AddField(
            model_name='site',
            name='author_twitter',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Twitter / X'),
        ),
        migrations.AddField(
            model_name='site',
            name='author_website',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Site personnel'),
        ),
    ]
