# Generated by Django 5.0.6 on 2026-05-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0014_site_author_bio_site_author_credentials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='wp_app_password',
            field=models.CharField(blank=True, default='', help_text='Application Password généré dans WP → Profil → Application Passwords.', max_length=200, verbose_name='WordPress — Application Password'),
        ),
        migrations.AddField(
            model_name='site',
            name='wp_url',
            field=models.URLField(blank=True, default='', help_text='Ex: https://monsite.ca (sans /wp-admin). Si renseigné, le site est en mode WordPress.', max_length=500, verbose_name='WordPress — URL du site'),
        ),
        migrations.AddField(
            model_name='site',
            name='wp_username',
            field=models.CharField(blank=True, default='', help_text="Le nom d'utilisateur WordPress qui possède l'Application Password.", max_length=100, verbose_name='WordPress — username'),
        ),
    ]
