# Generated by Django 5.0.6 on 2026-05-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0015_site_wp_app_password_site_wp_url_site_wp_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='public_blog_domain',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Hostname où le blog est servi (ex: blog.restaurant.ca, restofoo.blog-quebec.ca). Différent de `domain` qui désigne la marque.', max_length=255, verbose_name='Domaine du blog public'),
        ),
        migrations.AddField(
            model_name='site',
            name='theme_config',
            field=models.JSONField(blank=True, default=None, help_text='Couleurs, polices, logo pour le frontend public. Format: {brand_color, brand_fg, font_sans, font_display, logo_url}', null=True, verbose_name='Configuration du thème'),
        ),
    ]
