# Generated by Django 5.0.6 on 2026-05-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0019_site_shopify_access_token_site_shopify_blog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='webflow_collection_id',
            field=models.CharField(blank=True, default='', help_text='ID de la collection CMS où publier les articles (auto-rempli à la connexion).', max_length=64, verbose_name='Webflow — Collection ID'),
        ),
        migrations.AddField(
            model_name='site',
            name='webflow_field_map',
            field=models.JSONField(blank=True, default=None, help_text='Mapping de nos champs vers les slugs Webflow. Format: {title, slug, body, summary, image, status}. Auto-détecté à la connexion.', null=True, verbose_name='Webflow — Mapping de champs'),
        ),
        migrations.AddField(
            model_name='site',
            name='webflow_site_id',
            field=models.CharField(blank=True, default='', help_text='Identifiant du Webflow site (auto-rempli à la connexion).', max_length=64, verbose_name='Webflow — Site ID'),
        ),
        migrations.AddField(
            model_name='site',
            name='webflow_token',
            field=models.CharField(blank=True, default='', help_text='Site Token (Project Settings → Apps & Integrations → API access). Si renseigné avec un site_id et collection_id, le site est en mode Webflow.', max_length=300, verbose_name='Webflow — API token'),
        ),
    ]
