# Generated by Django 5.0.6 on 2026-05-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0020_site_webflow_collection_id_site_webflow_field_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Essai (gratuit)'), ('solo', 'Solo'), ('pro', 'Pro'), ('agency', 'Agence')], default='free', max_length=20),
        ),
    ]
