# Generated by Django 5.0.6 on 2026-05-07 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0021_alter_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyArticleQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(db_index=True, max_length=7)),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month_key'],
                'indexes': [models.Index(fields=['user', 'month_key'], name='sites_mgmt__user_id_17a479_idx')],
                'unique_together': {('user', 'month_key')},
            },
        ),
    ]
