# Generated by Django 5.0.6 on 2026-05-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0023_creditbalance_credittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='competitors',
            field=models.TextField(blank=True, default='', help_text="Une marque par ligne. Le générateur évitera de les mentionner et n'y mettra jamais de lien sortant.", verbose_name='Marques à NE PAS citer'),
        ),
    ]
