# Generated by Django 5.0.6 on 2026-05-14 21:43

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0024_add_site_competitors'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='SiteMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('article', 'Article publié'), ('kb', 'Knowledge base'), ('audit', 'Audit SEO'), ('decision', 'Décision éditoriale'), ('manual', 'Note manuelle')], db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True)),
                ('source_ref', models.CharField(blank=True, default='', help_text='Pointer back to the source (HostedPost slug, audit id, etc.). Used to wipe + re-index when the source mutates.', max_length=200)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='sites_mgmt.site')),
            ],
            options={
                'verbose_name': 'Mémoire site',
                'verbose_name_plural': 'Mémoires sites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', 'kind'], name='sites_mgmt__site_id_552b9a_idx'), models.Index(fields=['site', 'source_ref'], name='sites_mgmt__site_id_074f06_idx')],
            },
        ),
    ]
