# Generated by Django 5.0.6 on 2026-05-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0025_add_site_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedpost',
            name='feedback_rating',
            field=models.SmallIntegerField(default=0, help_text='0 = no feedback yet, 1 = good (boost chunks), -1 = bad (penalize)'),
        ),
        migrations.AddField(
            model_name='hostedpost',
            name='memory_chunks_used',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitememory',
            name='feedback_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
