# Generated by Django 5.0.6 on 2026-05-19 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0026_add_rag_feedback_loop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('domain_audited', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(db_index=True, default='public_audit', help_text="Funnel source: 'public_audit', 'wp_plugin', 'newsletter', etc.", max_length=50)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('locale', models.CharField(blank=True, default='', help_text='fr-CA, en-US, etc.', max_length=10)),
                ('consented_marketing', models.BooleanField(default=False, help_text='Loi 25 / RGPD: explicit opt-in to receive marketing. Without this, can only send transactional emails (e.g. the audit report itself).')),
                ('score_at_capture', models.IntegerField(blank=True, help_text='Composite SEO score at the moment of capture, for cohort analysis.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_to_user', models.ForeignKey(blank=True, help_text='Populated when this lead later signs up for a real account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_origins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead (audit gratuit)',
                'verbose_name_plural': 'Leads (audit gratuit)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='sites_mgmt__email_8a31bf_idx'), models.Index(fields=['source', '-created_at'], name='sites_mgmt__source_66a165_idx')],
            },
        ),
    ]
