# Generated by Django 5.0.6 on 2026-05-19 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0027_add_lead_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEmailSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(db_index=True, max_length=50)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('provider_message_id', models.CharField(blank=True, default='', help_text='Resend (or other provider) external id, for tracing.', max_length=120)),
                ('error', models.CharField(blank=True, default='', help_text="If non-empty, the send failed and we'll retry on the next cron tick.", max_length=300)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_sent', to='sites_mgmt.lead')),
            ],
            options={
                'verbose_name': 'Email envoyé (sequence lead)',
                'verbose_name_plural': 'Emails envoyés (sequence lead)',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['lead', 'step'], name='sites_mgmt__lead_id_91b88a_idx'), models.Index(fields=['-sent_at'], name='sites_mgmt__sent_at_f1cafb_idx')],
                'unique_together': {('lead', 'step')},
            },
        ),
    ]
