# Generated by Django 5.0.6 on 2026-05-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0028_add_lead_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='gsc_oauth_verifier_pending',
            field=models.CharField(blank=True, default='', help_text="Verifier PKCE genere lors du build de l'auth URL, replay au callback pour le fetch_token. Survit a un OAuth roundtrip via DB plutot que cache memoire (les workers gunicorn ne partagent pas LocMemCache). Efface apres succes ou echec - jamais sensitif tout seul.", max_length=128, verbose_name='GSC OAuth - PKCE verifier en cours'),
        ),
    ]
