# Generated by Django 5.0.6 on 2026-05-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0029_add_gsc_oauth_verifier_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='autopilot_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Si actif, Gridar génère automatiquement des articles selon la cadence configurée', verbose_name='Mode autopilote'),
        ),
        migrations.AddField(
            model_name='site',
            name='autopilot_last_error',
            field=models.TextField(blank=True, default='', help_text='Stack trace ou message si le dernier run a échoué (vidé au prochain succès)', verbose_name='Dernière erreur autopilote'),
        ),
        migrations.AddField(
            model_name='site',
            name='autopilot_last_run_at',
            field=models.DateTimeField(blank=True, help_text="Datetime du dernier article généré par l'autopilote (succès)", null=True, verbose_name='Dernier run autopilote'),
        ),
        migrations.AddField(
            model_name='site',
            name='autopilot_weekly_count',
            field=models.PositiveSmallIntegerField(default=2, help_text="Nombre d'articles que l'autopilote doit générer chaque semaine (1-7)", verbose_name='Articles par semaine'),
        ),
    ]
