# Generated by Django 5.0.6 on 2026-05-24 11:52

from django.db import migrations, models


def backfill_intent_via_regex(apps, schema_editor):
    """Classify each existing TrackedKeyword via the FR-CA regex heuristic.

    Runs once on deploy. Rows where the regex finds no strong signal stay
    at 'info' (the model default). Users can refine later with the
    "Reclasser avec l'IA" button or the inline badge editor.
    """
    from sites_mgmt.keyword_intent import classify_intent_heuristic
    TrackedKeyword = apps.get_model('sites_mgmt', 'TrackedKeyword')
    qs = TrackedKeyword.objects.all().only('id', 'keyword', 'intent')
    updates = []
    for tk in qs:
        guessed = classify_intent_heuristic(tk.keyword)
        if guessed and guessed != tk.intent:
            tk.intent = guessed
            updates.append(tk)
    if updates:
        TrackedKeyword.objects.bulk_update(updates, ['intent'], batch_size=500)


def noop(apps, schema_editor):
    """Reverse migration is a no-op - the column will just be dropped."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0030_site_autopilot_enabled_site_autopilot_last_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedkeyword',
            name='intent',
            field=models.CharField(choices=[('info', 'Informationnel'), ('commercial', 'Commercial'), ('transactional', 'Transactionnel'), ('local', 'Local')], db_index=True, default='info', help_text="Classification d'intent. Determine le type d'article que l'autopilote generera (guide / comparison / review / local).", max_length=20),
        ),
        migrations.RunPython(backfill_intent_via_regex, noop),
    ]
