# Generated by Django 5.0.6 on 2026-05-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0031_add_keyword_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedpost',
            name='published_at',
            field=models.DateField(blank=True, help_text="Set when status becomes 'published'. Drafts and scheduled-but-not-yet-fired posts have null here.", null=True),
        ),
    ]
