# Generated by Django 5.2.11 on 2026-06-01 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0033_add_autopilot_auto_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofShareToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='URL-safe random token. Rotated on revoke.', max_length=48, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof_token', to='sites_mgmt.site')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_since_publish', models.PositiveSmallIntegerField(choices=[(30, '30d'), (60, '60d'), (90, '90d')])),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateField(help_text='GSC window start. Usually published_at, capped at 16 months for GSC.')),
                ('period_end', models.DateField(help_text='GSC window end. Usually today (captured_at date).')),
                ('indexed', models.BooleanField(default=False, help_text='True if GSC returned any query rows for this page URL.')),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('avg_position', models.FloatField(blank=True, null=True)),
                ('top_queries', models.JSONField(blank=True, default=list)),
                ('delta_vs_baseline', models.JSONField(blank=True, default=dict, help_text='{"impressions": int, "clicks": int, "avg_position": float|null}')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='sites_mgmt.hostedpost')),
            ],
            options={
                'indexes': [models.Index(fields=['post', 'days_since_publish'], name='sites_mgmt__post_id_b8a590_idx'), models.Index(fields=['-captured_at'], name='sites_mgmt__capture_4911c8_idx')],
                'unique_together': {('post', 'days_since_publish')},
            },
        ),
        migrations.CreateModel(
            name='ArticleBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateField(help_text='GSC window start used for impressions/clicks/position.')),
                ('period_end', models.DateField(help_text='GSC window end (inclusive).')),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('avg_position', models.FloatField(blank=True, null=True)),
                ('top_queries', models.JSONField(blank=True, default=list, help_text='[{"query": str, "impressions": int, "clicks": int, "position": float}, ...]')),
                ('is_pre_gridar', models.BooleanField(default=False, help_text='True for the historical anchor captured at GSC-connect time.')),
                ('post', models.ForeignKey(blank=True, help_text='Null when the baseline is a pre-Gridar site-level anchor.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='sites_mgmt.hostedpost')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='sites_mgmt.site')),
            ],
            options={
                'indexes': [models.Index(fields=['site', '-captured_at'], name='sites_mgmt__site_id_823dd3_idx'), models.Index(fields=['post'], name='sites_mgmt__post_id_27dc73_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('site', 'post'), name='uniq_baseline_per_post')],
            },
        ),
    ]
