# Generated by Django 5.2.11 on 2026-06-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0034_proof_loop_baseline_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='business_model',
            field=models.CharField(choices=[('agency', 'Agence'), ('saas', 'SaaS'), ('ecommerce', 'E-commerce'), ('marketplace', 'Marketplace'), ('media', 'Média / Édition'), ('personal_blog', 'Blog personnel')], default='personal_blog', help_text="Détermine l'angle éditorial : SaaS pousse comparatifs/use-cases, e-commerce pousse fiches produits/buying guides, agence pousse case studies, etc. Champ obligatoire avant toute génération.", max_length=20, verbose_name="Modèle d'affaires"),
        ),
    ]
