# Generated by Django 5.2.11 on 2026-06-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0035_add_site_business_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedpost',
            name='schema_jsonld',
            field=models.JSONField(blank=True, default=dict, help_text="Auto-computed FAQPage JSON-LD (schema.org) injected in <head> at render time. Filled by HostedPost.save() when the content contains a '## FAQ' block with question/answer pairs; empty dict otherwise. Re-computed on every save so editing the FAQ in the editor keeps the markup in sync."),
        ),
    ]
