# Generated by Django 5.2.11 on 2026-06-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0036_add_hostedpost_schema_jsonld'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='autopilot_mode',
            field=models.CharField(choices=[('refresh_first', 'Refresh first - prioriser le rafraichissement des articles en perte de trafic'), ('create_only', 'Create only - generer uniquement de nouveaux articles'), ('balanced', 'Balanced - alterner refresh et creation (1 refresh / 2 creations)')], default='balanced', help_text='create_only: comportement legacy, ne genere que de nouveaux articles. refresh_first: prioritise systematiquement le refresh des articles en decay (impressions GSC -20% ou plus). balanced (defaut): alterne 1 refresh pour 2 creations.', max_length=20, verbose_name='Strategie autopilote'),
        ),
        migrations.AddField(
            model_name='site',
            name='min_refresh_interval_days',
            field=models.PositiveIntegerField(default=30, help_text="Empeche l'autopilote de rafraichir 2x de suite le meme article. Un article ne peut etre refreshe que si son updated_at est plus ancien que ce nombre de jours.", verbose_name="Intervalle minimum entre 2 refresh d'un meme article (jours)"),
        ),
    ]
