# Generated by Django 5.2.11 on 2026-06-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0037_add_site_autopilot_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='primary_cta_text',
            field=models.CharField(blank=True, default='', help_text="Phrase d'appel a l'action injectee en conclusion de chaque article genere (ex: 'Reserve ta consultation gratuite'). Le generateur construit un bouton/lien naturel a partir de ce texte + l'URL ci-dessous.", max_length=200, verbose_name='Texte du CTA principal'),
        ),
        migrations.AddField(
            model_name='site',
            name='primary_cta_url',
            field=models.URLField(blank=True, default='', help_text="Destination du CTA (ex: page de contact, page d'inscription, formulaire de devis). Inclus uniquement si le texte du CTA est aussi renseigne.", max_length=500, verbose_name='URL du CTA principal'),
        ),
    ]
