# Generated by Django 5.2.11 on 2026-06-09 00:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0038_add_site_primary_cta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostedLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='SEO <title>', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('h1', models.CharField(help_text='Visible H1, often longer / more emotional than the <title>.', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, default='', help_text='Sentence under the H1 - 1-2 lines max.', max_length=500)),
                ('hero_cta_text', models.CharField(blank=True, default='', max_length=80)),
                ('hero_cta_url', models.CharField(blank=True, default='', max_length=500)),
                ('value_props', models.JSONField(blank=True, default=list, help_text='[{"icon": str, "title": str, "description": str}, ...]')),
                ('social_proof', models.JSONField(blank=True, default=list, help_text='[{"type": "testimonial"|"logo"|"stat", ...}, ...]')),
                ('faq', models.JSONField(blank=True, default=list, help_text='[{"question": str, "answer": str}, ...]')),
                ('cta_bottom_text', models.CharField(blank=True, default='', max_length=80)),
                ('cta_bottom_url', models.CharField(blank=True, default='', max_length=500)),
                ('body_markdown', models.TextField(blank=True, default='', help_text='Optional free-form markdown rendered between value_props and FAQ.')),
                ('target_keyword', models.CharField(blank=True, db_index=True, default='', help_text='Primary keyword this landing targets.', max_length=200)),
                ('schema_type', models.CharField(choices=[('WebPage', 'WebPage'), ('Service', 'Service'), ('Product', 'Product'), ('LocalBusiness', 'LocalBusiness'), ('FAQPage', 'FAQPage'), ('Article', 'Article')], default='WebPage', max_length=20)),
                ('page_subtype', models.CharField(choices=[('service', 'Page service (transactionnel)'), ('product', 'Fiche produit'), ('pillar', 'Pillar page (cluster)'), ('comparison', 'Comparatif'), ('local', 'Page locale (geo)'), ('about', 'A propos'), ('contact', 'Contact'), ('generic', 'Generique')], db_index=True, default='generic', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie')], db_index=True, default='draft', max_length=20)),
                ('language', models.CharField(choices=[('fr', 'Francais'), ('en', 'English'), ('es', 'Espanol')], db_index=True, default='fr', max_length=2)),
                ('translation_group', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('cover_image', models.URLField(blank=True, default='', max_length=500)),
                ('meta_description', models.CharField(blank=True, default='', max_length=300)),
                ('schema_jsonld', models.JSONField(blank=True, default=dict, help_text='Auto-computed JSON-LD (Service/FAQPage/etc) injected at render time.')),
                ('published_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_landings', to='sites_mgmt.site')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['site', 'status'], name='sites_mgmt__site_id_177a7f_idx'), models.Index(fields=['site', 'page_subtype'], name='sites_mgmt__site_id_29534b_idx')],
                'unique_together': {('site', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='KeywordStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español')], default='fr', max_length=2)),
                ('intent', models.CharField(choices=[('transactional', 'Transactionnel'), ('commercial', 'Commercial (comparatif / review)'), ('informational', 'Informationnel'), ('navigational', 'Navigationnel (brand)'), ('local', 'Local')], db_index=True, default='informational', max_length=20)),
                ('intent_confidence', models.FloatField(default=0.5, help_text='0.0-1.0 confidence score from the classifier.')),
                ('business_model_detected', models.CharField(blank=True, choices=[('agency', 'Agence'), ('saas', 'SaaS'), ('ecommerce', 'E-commerce'), ('marketplace', 'Marketplace'), ('media', 'Média / Édition'), ('personal_blog', 'Blog personnel')], default='', help_text="Business model inferred from SERP (may differ from site's).", max_length=20)),
                ('serp_analysis', models.JSONField(blank=True, default=dict, help_text="{'top_results': [...], 'features': {...}, 'avg_word_count': int}")),
                ('proposed_structure', models.CharField(choices=[('single_landing', 'Une seule landing'), ('pillar_cluster', 'Pillar + cluster d articles'), ('blog_post', 'Article de blog standalone'), ('comparison_table', 'Page comparatif (vs)'), ('local_landing', 'Landing locale (geo)')], default='blog_post', max_length=30)),
                ('proposed_pages', models.JSONField(blank=True, default=list, help_text='[{"type":"landing|article","title":str,"slug":str,"keyword":str,"role":"pillar|cluster|alternative"}, ...]')),
                ('rationale', models.TextField(blank=True, default='', help_text='Plain-language explanation of why this structure was chosen.')),
                ('status', models.CharField(choices=[('draft', 'Brouillon (propose)'), ('approved', 'Approuve par l utilisateur'), ('generating', 'Generation en cours'), ('done', 'Pages generees'), ('rejected', 'Rejete')], db_index=True, default='draft', max_length=20)),
                ('generated_pages_fks', models.JSONField(blank=True, default=dict, help_text='{"landings": [<HostedLanding.id>, ...], "articles": [<HostedPost.id>, ...]} after approval.')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_strategies', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_strategies', to='sites_mgmt.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', 'status'], name='sites_mgmt__site_id_7b2e56_idx'), models.Index(fields=['site', 'intent'], name='sites_mgmt__site_id_346b72_idx')],
                'unique_together': {('site', 'keyword')},
            },
        ),
    ]
