# Generated by Django 5.2.11 on 2026-06-09 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0039_add_topic_cluster_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiVisibilityPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='Question posee aux LLMs pour mesurer la visibilite.', verbose_name='Prompt teste')),
                ('target_intent', models.CharField(blank=True, choices=[('informational', 'Informationnel'), ('commercial', 'Commercial / Comparatif'), ('transactional', 'Transactionnel'), ('navigational', 'Navigationnel'), ('local', 'Local')], max_length=20, null=True)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español')], default='fr', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_visibility_prompts', to='sites_mgmt.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiVisibilityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('chatgpt', 'ChatGPT'), ('perplexity', 'Perplexity'), ('gemini', 'Gemini'), ('searchgpt', 'SearchGPT'), ('claude', 'Claude')], db_index=True, max_length=20)),
                ('response_excerpt', models.TextField(blank=True, default='', help_text='Premiers ~500 caracteres de la reponse du LLM.')),
                ('is_cited', models.BooleanField(db_index=True, default=False, help_text='True si le domaine du site apparait dans la reponse.')),
                ('citation_url', models.URLField(blank=True, max_length=500, null=True)),
                ('citation_rank', models.PositiveIntegerField(blank=True, help_text='Position de la citation dans la reponse (1 = premiere).', null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='sites_mgmt.aivisibilityprompt')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aivisibilityprompt',
            index=models.Index(fields=['site', '-created_at'], name='sites_mgmt__site_id_77a52a_idx'),
        ),
        migrations.AddIndex(
            model_name='aivisibilityresult',
            index=models.Index(fields=['prompt', 'engine'], name='sites_mgmt__prompt__99974b_idx'),
        ),
        migrations.AddIndex(
            model_name='aivisibilityresult',
            index=models.Index(fields=['prompt', '-checked_at'], name='sites_mgmt__prompt__d2d02d_idx'),
        ),
    ]
