# Generated by Django 5.0.6 on 2026-06-09 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0040_add_ai_visibility_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, help_text='Copie du mot-clé pour requêtes sans join.', max_length=255)),
                ('intent', models.CharField(choices=[('info', 'Informationnel'), ('commercial', 'Commercial'), ('transactional', 'Transactionnel'), ('local', 'Local')], db_index=True, default='commercial', max_length=20)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español')], default='fr', max_length=2)),
                ('concept', models.JSONField(blank=True, default=dict)),
                ('estimate', models.JSONField(blank=True, default=dict)),
                ('current_position', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'Élevée'), ('medium', 'Moyenne'), ('low', 'Faible')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('proposed', 'Proposée'), ('approved', 'Approuvée'), ('dismissed', 'Écartée'), ('done', 'Page créée')], db_index=True, default='proposed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refreshed_at', models.DateTimeField(blank=True, help_text="Dernier appel Claude. Sert à éviter de re-générer un concept tant qu'il n'a pas vieilli.", null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_landing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_opportunities', to='sites_mgmt.hostedlanding')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_opportunities', to='sites_mgmt.site')),
                ('tracked_keyword', models.ForeignKey(blank=True, help_text="Mot-clé source. NULL si l'opportunité est issue d'une suggestion machine plutôt que d'un keyword tracké.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategic_opportunities', to='sites_mgmt.trackedkeyword')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['site', 'status'], name='sites_mgmt__site_id_70df34_idx'), models.Index(fields=['site', '-created_at'], name='sites_mgmt__site_id_5a6b4c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='strategicopportunity',
            constraint=models.UniqueConstraint(fields=('site', 'keyword', 'language'), name='uniq_opportunity_per_keyword'),
        ),
    ]
