# Generated by Django 5.0.6 on 2026-06-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0041_strategicopportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Loi 25 / RGPD: timestamp of the opt-out. Set on EVERY Lead row sharing the same email (the audit page creates one row per audit, not per address). Blocks all marketing steps; the transactional j0 report still goes out when the person explicitly requests a new audit.', null=True),
        ),
    ]
