# Generated by Django 5.0.6 on 2026-06-13 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0042_lead_unsubscribed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('payload', models.JSONField(default=dict, help_text='Full audit report (score, pagespeed, keyword positions, recos, crawl) exactly as returned by the public audit.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Rapport d'audit public (partageable)",
                'verbose_name_plural': "Rapports d'audit publics (partageables)",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='report_token',
            field=models.UUIDField(blank=True, db_index=True, help_text='Token of the PublicAuditReport captured with this audit, so the J+0 email can link to the shareable report page (gridar.app/rapport/<token>).', null=True),
        ),
    ]
