# Generated by Django 5.2.11 on 2026-02-20 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.TextField(verbose_name='Extrait')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('author', models.CharField(default='Admin', max_length=100, verbose_name='Auteur')),
                ('cover_image', models.URLField(blank=True, max_length=500, verbose_name='Image de couverture')),
                ('reading_time', models.PositiveIntegerField(default=5, verbose_name='Temps de lecture (min)')),
                ('featured', models.BooleanField(default=False, verbose_name='En vedette')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie'), ('scheduled', 'Planifie')], default='published', max_length=20, verbose_name='Statut')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Publication planifiee')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('published_at', models.DateField(verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Derniere modification')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Categorie')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='blog_blogpo_publish_e75c11_idx'), models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'), models.Index(fields=['featured'], name='blog_blogpo_feature_0ec342_idx')],
            },
        ),
    ]
