# Generated by Django 5.2.11 on 2026-06-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_language_blogpost_translation_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='Date de publication'),
        ),
    ]
