# Generated by Django 5.2.11 on 2026-02-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0002_alter_site_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='knowledge_base',
            field=models.TextField(blank=True, default='', help_text="Contexte personnel pour la generation d'articles (qui tu es, tes projets, ton ton, etc.)", verbose_name='Base de connaissances'),
        ),
    ]
