# Generated by Django 5.2.11 on 2026-02-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0004_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='blog_config',
            field=models.JSONField(blank=True, default=None, help_text="Mapping des tables/colonnes si le site n'utilise pas les tables blog_* standard", null=True, verbose_name='Config tables blog'),
        ),
    ]
