# Generated by Django 5.2.11 on 2026-04-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0005_add_blog_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='vercel_deploy_hook',
            field=models.URLField(blank=True, default='', help_text="URL du Deploy Hook Vercel pour redéployer le site après modification d'articles", max_length=500, verbose_name='Vercel Deploy Hook'),
        ),
    ]
