# Generated by Django 5.2.11 on 2026-04-18 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='language',
            field=models.CharField(choices=[('fr', 'Francais'), ('en', 'English'), ('es', 'Espanol')], db_index=True, default='fr', max_length=2, verbose_name='Langue'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text="Meme UUID partage par les traductions d'un meme article", verbose_name='Groupe de traduction'),
        ),
    ]
