"""Article-quota helpers.

Each user has a monthly article-generation budget defined by their subscription
plan (`Subscription.get_limits()['articles_per_month']`). We track usage in a
`MonthlyArticleQuota` row keyed by `YYYY-MM`. The row is created lazily on the
first successful generation in a month, then incremented atomically with F().

Quota check raises DRF's PermissionDenied if exhausted; otherwise returns
`(used, limit)` so callers can pass the info to the response (or skip the
increment when `dry_run`).
"""
from __future__ import annotations

from django.db.models import F
from django.utils import timezone
from rest_framework.exceptions import PermissionDenied

from .models import MonthlyArticleQuota, Subscription


def current_month_key() -> str:
    """Return the YYYY-MM key for the current UTC month."""
    now = timezone.now()
    return f"{now.year:04d}-{now.month:02d}"


def get_articles_used(user) -> int:
    """Count of articles generated by `user` this month."""
    row = MonthlyArticleQuota.objects.filter(
        user=user, month_key=current_month_key()
    ).first()
    return row.count if row else 0


def get_articles_limit(user) -> int | None:
    """Plan's `articles_per_month` limit. None = unlimited."""
    sub, _ = Subscription.objects.get_or_create(user=user)
    return (sub.get_limits() or {}).get('articles_per_month')


def check_article_quota(user) -> tuple[int, int | None]:
    """Raise `PermissionDenied` if `user` has exhausted their monthly quota.
    Returns `(used, limit)` on success. `limit=None` means unlimited.
    """
    limit = get_articles_limit(user)
    used = get_articles_used(user)
    if limit is not None and used >= limit:
        raise PermissionDenied(
            f"Quota mensuel atteint ({used}/{limit}). Mets ton plan à niveau "
            f"sur /billing pour continuer à générer ce mois-ci."
        )
    return (used, limit)


def increment_article_quota(user) -> int:
    """Increment usage counter atomically. Returns the new count.
    Caller should invoke this AFTER a successful (non-dry-run) generation.
    """
    key = current_month_key()
    row, created = MonthlyArticleQuota.objects.get_or_create(
        user=user, month_key=key, defaults={'count': 1}
    )
    if created:
        return 1
    MonthlyArticleQuota.objects.filter(pk=row.pk).update(count=F('count') + 1)
    row.refresh_from_db(fields=['count'])
    return row.count
