from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    SiteViewSet, UserProfileView,
    SitePostsView, SitePostDetailView,
    SiteStatsView, SiteCategoriesView, SiteTagsView, SiteCannibalizationView,
    PexelsSearchView, SerperImageSearchView, GenerateImageView,
    GenerateArticleView, GenerateInlineView, GenerateTagsView,
    UploadImageView, ServeImageView, SEOAuditView, SEOFixView, SEOSuggestView,
    SEOSynonymsView, SEOCacheClearView, TranslatePostView, CompetitorAnalysisView,
    KeywordResearchView, ContentBriefView, PAAView, HreflangCheckView,
    BulkSEOAuditView, TrackedKeywordsView, TrackedKeywordDetailView,
    TrackedKeywordReclassifyView,
    RankSnapshotView, RankHistoryView, ContentDecayView, TopicClusterView,
    LinkGraphView, ReadabilityView, RedirectsView, RedirectDetailView,
    BrokenLinksView, CommunityQuestionsView, LexiconCheckView,
    LocalBusinessSchemaView, PersonSchemaView, SearchTrendsView,
    ImageSEOSuggestView, MultiDomainStatsView, WeeklyDigestView,
    WordPressDiscoverView, WordPressConnectView,
    ShopifyDiscoverView, ShopifyConnectView,
    WebflowDiscoverView, WebflowCollectionsView, WebflowConnectView,
    BrandingScanView, SuggestCompetitorsView, SuggestKeywordsView,
    SiteMemoryView, SiteMemoryDetailView, SiteMemoryRebuildView,
    PostFeedbackView, SiteAuditAggregatorView,
    BlogDomainProvisionView, BlogDomainStatusView, BlogDomainRemoveView,
    PublicAuditView, PublicLeadCaptureView, PublicAuditStatsView,
    PublicPositionCheckView,
    PublicReportView,
    PublicUnsubscribeView, PublicUnsubscribeOneClickView,
    WPConnectorView,
    SiteSitemapView, SiteRSSView,
    BillingMeView, BillingCheckoutView, BillingPortalView, BillingWebhookView,
    BillingCreditsView, BillingCreditsCheckoutView,
    PlagiarismCheckView, SiteSeoScoreView, AIOverviewReadinessView,
    CheckRenderabilityView,
    PageSpeedView, LinkSuggestionsView, BacklinksView, SEOSchemaView,
    PublicSiteView, PublicSiteByDomainView, PublicPostsView, PublicPostDetailView,
    PublicTranslationsView, PublicCategoriesView,
    PublicLandingsView, PublicLandingDetailView,
    GSCOAuthUrlView, GSCOAuthCallbackView, GSCDisconnectView, GSCQueriesView,
    AutopilotConfigView, AutopilotRunView,
)
from .api_v1 import (
    V1MeView, V1SitesView, V1ArticlesView, V1ArticleDetailView, V1GenerateView,
    V1AuditView, V1BriefView, V1KeywordsView, V1RankSnapshotView,
    V1DigestView, TokenManagementView, TokenRevokeView, IssueMcpTokenView,
    V1SiteDetailView, V1SiteUpdateView,
    V1ArticleCreateView, V1ArticleMutateView,
    V1KeywordTrackView, V1KeywordUntrackView,
    V1CompetitorsAnalyzeView, V1ContentDecayView, V1BrokenLinksView,
    V1HreflangCheckView, V1CannibalizationView, V1LinkSuggestionsView,
    V1BulkAuditView, V1ReadabilityView, V1PlagiarismView,
    V1GSCQueriesView, V1AutopilotConfigView, V1AutopilotRunView,
    V1MemoriesListView, V1MemoryDetailView, V1MemoryRebuildView,
    V1ProofSummaryView, V1ProofAttributionView, V1ProofShareView,
    V1SuggestKeywordsView, V1SuggestCompetitorsView,
    V1KeywordResearchView, V1PageSpeedView, V1PAAView,
    V1GenerateSisterArticleView,
    V1ClassifyIntentView, V1ProposeKeywordStrategyView, V1ApproveStrategyView,
    V1CreateLandingView, V1GenerateLandingView, V1LinkPagesView,
    V1SiteSeoScoreView, V1AIOverviewReadinessView,
    V1CheckRenderabilityView, V1LinkOpportunitiesView,
    V1SerpAnalyzeView,
    V1AiVisibilitySummaryView, V1AiVisibilityPromptsView, V1AiVisibilityRunView,
    V1AiVisibilitySuggestView,
    V1StrategicOpportunitiesView, V1StrategicOpportunitiesRefreshView,
    V1StrategicOpportunityActionView,
    V1LandingPromptView, V1OpportunityPromptView,
)
from .views_proof import (
    ProofBaselineView, ProofAttributionView, ProofSummaryView,
    ProofShareView, PublicProofView,
)

router = DefaultRouter()
router.register(r'sites', SiteViewSet, basename='site')

urlpatterns = [
    path('auth/me/', UserProfileView.as_view(), name='user-profile'),
    path('sites/<int:site_id>/posts/', SitePostsView.as_view(), name='site-posts'),
    path('sites/<int:site_id>/posts/<slug:slug>/', SitePostDetailView.as_view(), name='site-post-detail'),
    path('sites/<int:site_id>/stats/', SiteStatsView.as_view(), name='site-stats'),
    path('sites/<int:site_id>/categories/', SiteCategoriesView.as_view(), name='site-categories'),
    path('sites/<int:site_id>/tags/', SiteTagsView.as_view(), name='site-tags'),
    path('sites/<int:site_id>/cannibalization/', SiteCannibalizationView.as_view(), name='site-cannibalization'),
    path('sites/<int:site_id>/audit-all/', BulkSEOAuditView.as_view(), name='site-audit-all'),
    path('sites/<int:site_id>/keywords/', TrackedKeywordsView.as_view(), name='site-keywords'),
    path('sites/<int:site_id>/keywords/reclassify/', TrackedKeywordReclassifyView.as_view(), name='site-keywords-reclassify'),
    path('sites/<int:site_id>/keywords/<int:pk>/', TrackedKeywordDetailView.as_view(), name='site-keyword-detail'),
    path('sites/<int:site_id>/rank-snapshot/', RankSnapshotView.as_view(), name='site-rank-snapshot'),
    path('sites/<int:site_id>/rank-history/', RankHistoryView.as_view(), name='site-rank-history'),
    path('sites/<int:site_id>/content-decay/', ContentDecayView.as_view(), name='site-content-decay'),
    path('sites/<int:site_id>/topic-clusters/', TopicClusterView.as_view(), name='site-topic-clusters'),
    path('sites/<int:site_id>/link-graph/', LinkGraphView.as_view(), name='site-link-graph'),
    path('readability/', ReadabilityView.as_view(), name='readability'),
    path('sites/<int:site_id>/redirects/', RedirectsView.as_view(), name='site-redirects'),
    path('sites/<int:site_id>/redirects/<int:pk>/', RedirectDetailView.as_view(), name='site-redirect-detail'),
    path('sites/<int:site_id>/broken-links/', BrokenLinksView.as_view(), name='site-broken-links'),
    path('community-questions/', CommunityQuestionsView.as_view(), name='community-questions'),
    path('lexicon-check/', LexiconCheckView.as_view(), name='lexicon-check'),
    path('sites/<int:site_id>/local-business-schema/', LocalBusinessSchemaView.as_view(), name='site-local-business-schema'),
    path('sites/<int:site_id>/person-schema/', PersonSchemaView.as_view(), name='site-person-schema'),
    path('trends/', SearchTrendsView.as_view(), name='search-trends'),
    path('image-suggest/', ImageSEOSuggestView.as_view(), name='image-suggest'),
    path('multi-domain-stats/', MultiDomainStatsView.as_view(), name='multi-domain-stats'),
    path('sites/<int:site_id>/weekly-digest/', WeeklyDigestView.as_view(), name='site-weekly-digest'),
    path('wp/discover/', WordPressDiscoverView.as_view(), name='wp-discover'),
    path('wp/connect/', WordPressConnectView.as_view(), name='wp-connect'),
    path('shopify/discover/', ShopifyDiscoverView.as_view(), name='shopify-discover'),
    path('shopify/connect/', ShopifyConnectView.as_view(), name='shopify-connect'),
    path('webflow/discover/', WebflowDiscoverView.as_view(), name='webflow-discover'),
    path('webflow/collections/', WebflowCollectionsView.as_view(), name='webflow-collections'),
    path('webflow/connect/', WebflowConnectView.as_view(), name='webflow-connect'),
    path('branding/scan/', BrandingScanView.as_view(), name='branding-scan'),
    # Public XML feeds (no auth - must be reachable by Googlebot)
    path('sites/<int:site_id>/sitemap.xml', SiteSitemapView.as_view(), name='site-sitemap-xml'),
    path('sites/<int:site_id>/rss.xml', SiteRSSView.as_view(), name='site-rss-xml'),
    path('billing/me/', BillingMeView.as_view(), name='billing-me'),
    path('billing/checkout/', BillingCheckoutView.as_view(), name='billing-checkout'),
    path('billing/portal/', BillingPortalView.as_view(), name='billing-portal'),
    path('billing/webhook/', BillingWebhookView.as_view(), name='billing-webhook'),
    path('billing/credits/', BillingCreditsView.as_view(), name='billing-credits'),
    path('billing/credits/buy/', BillingCreditsCheckoutView.as_view(), name='billing-credits-buy'),
    path('plagiarism-check/', PlagiarismCheckView.as_view(), name='plagiarism-check'),
    path('sites/<int:site_id>/generate/', GenerateArticleView.as_view(), name='site-generate-article'),
    path('sites/<int:site_id>/generate-inline/', GenerateInlineView.as_view(), name='site-generate-inline'),
    path('sites/<int:site_id>/link-suggestions/', LinkSuggestionsView.as_view(), name='site-link-suggestions'),
    path('pexels/search/', PexelsSearchView.as_view(), name='pexels-search'),
    path('serper/images/', SerperImageSearchView.as_view(), name='serper-images'),
    path('generate-image/', GenerateImageView.as_view(), name='generate-image'),
    path('upload-image/', UploadImageView.as_view(), name='upload-image'),
    path('images/<uuid:uid>/', ServeImageView.as_view(), name='serve-image'),
    path('generate-tags/', GenerateTagsView.as_view(), name='generate-tags'),
    path('translate/', TranslatePostView.as_view(), name='translate-post'),
    path('seo-audit/', SEOAuditView.as_view(), name='seo-audit'),
    path('seo-fix/', SEOFixView.as_view(), name='seo-fix'),
    path('seo-suggest/', SEOSuggestView.as_view(), name='seo-suggest'),
    path('seo-synonyms/', SEOSynonymsView.as_view(), name='seo-synonyms'),
    path('seo-cache/clear/', SEOCacheClearView.as_view(), name='seo-cache-clear'),
    path('competitors/', CompetitorAnalysisView.as_view(), name='competitors'),
    path('sites/<int:site_id>/suggest-competitors/', SuggestCompetitorsView.as_view(), name='site-suggest-competitors'),
    path('sites/<int:site_id>/suggest-keywords/', SuggestKeywordsView.as_view(), name='site-suggest-keywords'),
    path('sites/<int:site_id>/memories/', SiteMemoryView.as_view(), name='site-memories'),
    path('sites/<int:site_id>/memories/rebuild/', SiteMemoryRebuildView.as_view(), name='site-memories-rebuild'),
    path('sites/<int:site_id>/memories/<int:pk>/', SiteMemoryDetailView.as_view(), name='site-memory-detail'),
    path('sites/<int:site_id>/posts/<slug:slug>/feedback/', PostFeedbackView.as_view(), name='post-feedback'),
    path('sites/<int:site_id>/site-audit/', SiteAuditAggregatorView.as_view(), name='site-audit-aggregator'),
    path('sites/<int:site_id>/seo-score/', SiteSeoScoreView.as_view(), name='site-seo-score'),
    path('sites/<int:site_id>/posts/<slug:slug>/ai-overview-readiness/', AIOverviewReadinessView.as_view(), name='site-post-ai-overview-readiness'),
    path('sites/<int:site_id>/blog-domain/provision/', BlogDomainProvisionView.as_view(), name='blog-domain-provision'),
    path('sites/<int:site_id>/blog-domain/status/', BlogDomainStatusView.as_view(), name='blog-domain-status'),
    path('sites/<int:site_id>/blog-domain/', BlogDomainRemoveView.as_view(), name='blog-domain-remove'),
    # Public audit lead magnet (no auth)
    path('public/audit/', PublicAuditView.as_view(), name='public-audit'),
    path('public/position-check/', PublicPositionCheckView.as_view(), name='public-position-check'),
    path('public/leads/', PublicLeadCaptureView.as_view(), name='public-lead-capture'),
    path('public/audit-stats/', PublicAuditStatsView.as_view(), name='public-audit-stats'),
    path('public/report/<uuid:token>/', PublicReportView.as_view(), name='public-report'),
    path('public/unsubscribe/', PublicUnsubscribeView.as_view(), name='public-unsubscribe'),
    path('public/unsubscribe/one-click/', PublicUnsubscribeOneClickView.as_view(), name='public-unsubscribe-one-click'),
    # WordPress plugin 1-click connector
    path('v1/wp-connector/connect/', WPConnectorView.as_view(), name='v1-wp-connector-connect'),
    path('keyword-research/', KeywordResearchView.as_view(), name='keyword-research'),
    path('content-brief/', ContentBriefView.as_view(), name='content-brief'),
    path('paa/', PAAView.as_view(), name='paa'),
    path('hreflang-check/', HreflangCheckView.as_view(), name='hreflang-check'),
    path('page-speed/', PageSpeedView.as_view(), name='page-speed'),
    path('backlinks/', BacklinksView.as_view(), name='backlinks'),
    path('seo-schema/', SEOSchemaView.as_view(), name='seo-schema'),
    # Autopilot mode (scheduled hands-off generation)
    path('sites/<int:site_id>/autopilot/', AutopilotConfigView.as_view(), name='site-autopilot-config'),
    path('sites/<int:site_id>/autopilot/run/', AutopilotRunView.as_view(), name='site-autopilot-run'),
    # Google Search Console integration
    path('sites/<int:site_id>/gsc/oauth-url/', GSCOAuthUrlView.as_view(), name='gsc-oauth-url'),
    path('sites/<int:site_id>/gsc/oauth-callback/', GSCOAuthCallbackView.as_view(), name='gsc-oauth-callback'),
    path('sites/<int:site_id>/gsc/disconnect/', GSCDisconnectView.as_view(), name='gsc-disconnect'),
    path('sites/<int:site_id>/gsc/queries/', GSCQueriesView.as_view(), name='gsc-queries'),
    # Proof loop (baseline + attribution)
    path('sites/<int:site_id>/proof/baseline/', ProofBaselineView.as_view(), name='site-proof-baseline'),
    path('sites/<int:site_id>/proof/attribution/', ProofAttributionView.as_view(), name='site-proof-attribution'),
    path('sites/<int:site_id>/proof/summary/', ProofSummaryView.as_view(), name='site-proof-summary'),
    path('sites/<int:site_id>/proof/share/', ProofShareView.as_view(), name='site-proof-share'),
    path('public/proof/<str:token>/', PublicProofView.as_view(), name='public-proof'),
    # Public API - for site frontends
    path('public/site-by-domain/', PublicSiteByDomainView.as_view(), name='public-site-by-domain'),
    path('public/sites/<int:site_id>/', PublicSiteView.as_view(), name='public-site'),
    path('public/sites/<int:site_id>/posts/', PublicPostsView.as_view(), name='public-posts'),
    path('public/sites/<int:site_id>/posts/<slug:slug>/', PublicPostDetailView.as_view(), name='public-post-detail'),
    path('public/sites/<int:site_id>/posts/<slug:slug>/translations/', PublicTranslationsView.as_view(), name='public-translations'),
    path('public/sites/<int:site_id>/landings/', PublicLandingsView.as_view(), name='public-landings'),
    path('public/sites/<int:site_id>/landings/<slug:slug>/', PublicLandingDetailView.as_view(), name='public-landing-detail'),
    path('public/sites/<int:site_id>/categories/', PublicCategoriesView.as_view(), name='public-categories'),
    # Public developer API v1 (Bearer ApiToken auth)
    path('v1/me/', V1MeView.as_view(), name='v1-me'),
    path('v1/sites/', V1SitesView.as_view(), name='v1-sites'),
    path('v1/sites/<int:site_id>/articles/', V1ArticlesView.as_view(), name='v1-articles'),
    # Must come BEFORE the catch-all <slug:slug>/ pattern below (else "manual"
    # is consumed as a slug).
    path('v1/sites/<int:site_id>/articles/manual/', V1ArticleCreateView.as_view(), name='v1-article-create'),
    path('v1/sites/<int:site_id>/articles/<slug:slug>/manual/', V1ArticleMutateView.as_view(), name='v1-article-mutate'),
    path('v1/sites/<int:site_id>/articles/<slug:slug>/generate-sister-article/', V1GenerateSisterArticleView.as_view(), name='v1-generate-sister-article'),
    path('v1/sites/<int:site_id>/articles/<slug:slug>/ai-overview-readiness/', V1AIOverviewReadinessView.as_view(), name='v1-ai-overview-readiness'),
    path('v1/sites/<int:site_id>/articles/<slug:slug>/', V1ArticleDetailView.as_view(), name='v1-article-detail'),
    path('v1/sites/<int:site_id>/generate/', V1GenerateView.as_view(), name='v1-generate'),
    path('v1/audit/', V1AuditView.as_view(), name='v1-audit'),
    path('v1/brief/', V1BriefView.as_view(), name='v1-brief'),
    path('v1/sites/<int:site_id>/keywords/', V1KeywordsView.as_view(), name='v1-keywords'),
    path('v1/sites/<int:site_id>/keywords/snapshot/', V1RankSnapshotView.as_view(), name='v1-rank-snapshot'),
    path('v1/sites/<int:site_id>/digest/weekly/', V1DigestView.as_view(), name='v1-digest'),
    # Account-level token management (JWT auth)
    path('account/api-tokens/', TokenManagementView.as_view(), name='api-tokens'),
    path('account/api-tokens/<int:pk>/', TokenRevokeView.as_view(), name='api-token-revoke'),
    # MCP OAuth token issuance bridge (called from /oauth/mcp-authorize page)
    path('auth/issue-mcp-token/', IssueMcpTokenView.as_view(), name='auth-issue-mcp-token'),
    # Extended public API v1 (Bearer ApiToken) - 0.2 / mcp-server expansion
    path('v1/sites/<int:site_id>/detail/', V1SiteDetailView.as_view(), name='v1-site-detail'),
    path('v1/sites/<int:site_id>/update/', V1SiteUpdateView.as_view(), name='v1-site-update'),
    path('v1/sites/<int:site_id>/keywords/track/', V1KeywordTrackView.as_view(), name='v1-keyword-track'),
    path('v1/sites/<int:site_id>/keywords/<int:pk>/untrack/', V1KeywordUntrackView.as_view(), name='v1-keyword-untrack'),
    path('v1/competitors/', V1CompetitorsAnalyzeView.as_view(), name='v1-competitors'),
    path('v1/sites/<int:site_id>/content-decay/', V1ContentDecayView.as_view(), name='v1-content-decay'),
    path('v1/sites/<int:site_id>/broken-links/', V1BrokenLinksView.as_view(), name='v1-broken-links'),
    path('v1/hreflang-check/', V1HreflangCheckView.as_view(), name='v1-hreflang-check'),
    path('v1/sites/<int:site_id>/cannibalization/', V1CannibalizationView.as_view(), name='v1-cannibalization'),
    path('v1/sites/<int:site_id>/link-suggestions/', V1LinkSuggestionsView.as_view(), name='v1-link-suggestions'),
    path('v1/sites/<int:site_id>/audit-all/', V1BulkAuditView.as_view(), name='v1-bulk-audit'),
    path('v1/readability/', V1ReadabilityView.as_view(), name='v1-readability'),
    path('v1/plagiarism/', V1PlagiarismView.as_view(), name='v1-plagiarism'),
    path('v1/sites/<int:site_id>/gsc-queries/', V1GSCQueriesView.as_view(), name='v1-gsc-queries'),
    path('v1/sites/<int:site_id>/autopilot/', V1AutopilotConfigView.as_view(), name='v1-autopilot'),
    path('v1/sites/<int:site_id>/autopilot/run/', V1AutopilotRunView.as_view(), name='v1-autopilot-run'),
    path('v1/sites/<int:site_id>/memories/', V1MemoriesListView.as_view(), name='v1-memories'),
    path('v1/sites/<int:site_id>/memories/<int:pk>/', V1MemoryDetailView.as_view(), name='v1-memory-detail'),
    path('v1/sites/<int:site_id>/memories/rebuild/', V1MemoryRebuildView.as_view(), name='v1-memory-rebuild'),
    path('v1/sites/<int:site_id>/proof/summary/', V1ProofSummaryView.as_view(), name='v1-proof-summary'),
    path('v1/sites/<int:site_id>/proof/attribution/', V1ProofAttributionView.as_view(), name='v1-proof-attribution'),
    path('v1/sites/<int:site_id>/proof/share/', V1ProofShareView.as_view(), name='v1-proof-share'),
    path('v1/sites/<int:site_id>/suggest-keywords/', V1SuggestKeywordsView.as_view(), name='v1-suggest-keywords'),
    path('v1/sites/<int:site_id>/suggest-competitors/', V1SuggestCompetitorsView.as_view(), name='v1-suggest-competitors'),
    path('v1/keyword-research/', V1KeywordResearchView.as_view(), name='v1-keyword-research'),
    path('v1/page-speed/', V1PageSpeedView.as_view(), name='v1-page-speed'),
    path('v1/paa/', V1PAAView.as_view(), name='v1-paa'),
    # Topic Cluster Planner (2026-06-08)
    path('v1/classify-intent/', V1ClassifyIntentView.as_view(), name='v1-classify-intent'),
    path('v1/sites/<int:site_id>/keyword-strategy/', V1ProposeKeywordStrategyView.as_view(), name='v1-propose-keyword-strategy'),
    path('v1/sites/<int:site_id>/keyword-strategy/<int:strategy_id>/approve/', V1ApproveStrategyView.as_view(), name='v1-approve-strategy'),
    path('v1/sites/<int:site_id>/landings/manual/', V1CreateLandingView.as_view(), name='v1-landing-create'),
    path('v1/sites/<int:site_id>/landings/generate/', V1GenerateLandingView.as_view(), name='v1-landing-generate'),
    path('v1/sites/<int:site_id>/link-pages/', V1LinkPagesView.as_view(), name='v1-link-pages'),
    path('v1/sites/<int:site_id>/seo-score/', V1SiteSeoScoreView.as_view(), name='v1-site-seo-score'),
    # Renderability check (P1 #9, 2026-06-08)
    path('check-renderability/', CheckRenderabilityView.as_view(), name='check-renderability'),
    path('v1/check-renderability/', V1CheckRenderabilityView.as_view(), name='v1-check-renderability'),
    # Link Opportunities (P2 #11, 2026-06-08)
    path('v1/link-opportunities/', V1LinkOpportunitiesView.as_view(), name='v1-link-opportunities'),
    # SERP Analyzer (2026-06-08)
    path('v1/sites/<int:site_id>/serp-analyze/', V1SerpAnalyzeView.as_view(), name='v1-serp-analyze'),
    # AI Visibility tracking (2026-06-08)
    path('v1/sites/<int:site_id>/ai-visibility/summary/', V1AiVisibilitySummaryView.as_view(), name='v1-ai-visibility-summary'),
    path('v1/sites/<int:site_id>/ai-visibility/prompts/', V1AiVisibilityPromptsView.as_view(), name='v1-ai-visibility-prompts'),
    path('v1/sites/<int:site_id>/ai-visibility/run/', V1AiVisibilityRunView.as_view(), name='v1-ai-visibility-run'),
    path('v1/sites/<int:site_id>/ai-visibility/suggest/', V1AiVisibilitySuggestView.as_view(), name='v1-ai-visibility-suggest'),
    # Strategic Opportunities (2026-06-09)
    path('v1/sites/<int:site_id>/strategic-opportunities/',
         V1StrategicOpportunitiesView.as_view(),
         name='v1-strategic-opportunities'),
    path('v1/sites/<int:site_id>/strategic-opportunities/refresh/',
         V1StrategicOpportunitiesRefreshView.as_view(),
         name='v1-strategic-opportunities-refresh'),
    # Prompt export routes MUST be declared before the generic
    # <str:action> route below, otherwise 'prompt' would be swallowed
    # by the action matcher.
    path('v1/sites/<int:site_id>/strategic-opportunities/<int:op_id>/prompt/',
         V1OpportunityPromptView.as_view(),
         name='v1-strategic-opportunity-prompt'),
    path('v1/sites/<int:site_id>/landings/<int:landing_id>/prompt/',
         V1LandingPromptView.as_view(),
         name='v1-landing-prompt'),
    path('v1/sites/<int:site_id>/strategic-opportunities/<int:op_id>/<str:action>/',
         V1StrategicOpportunityActionView.as_view(),
         name='v1-strategic-opportunity-action'),
    path('', include(router.urls)),
]
