from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    SiteViewSet, UserProfileView,
    SitePostsView, SitePostDetailView,
    SiteStatsView, SiteCategoriesView, SiteTagsView, SiteCannibalizationView,
    PexelsSearchView, SerperImageSearchView, GenerateImageView,
    GenerateArticleView, GenerateInlineView, GenerateTagsView,
    UploadImageView, ServeImageView, SEOAuditView, SEOFixView, SEOSuggestView,
    SEOSynonymsView, SEOCacheClearView, TranslatePostView, CompetitorAnalysisView,
    KeywordResearchView, ContentBriefView, PAAView, HreflangCheckView,
    BulkSEOAuditView, TrackedKeywordsView, TrackedKeywordDetailView,
    RankSnapshotView, RankHistoryView, ContentDecayView, TopicClusterView,
    LinkGraphView, ReadabilityView, RedirectsView, RedirectDetailView,
    BrokenLinksView, CommunityQuestionsView, LexiconCheckView,
    LocalBusinessSchemaView, PersonSchemaView, SearchTrendsView,
    ImageSEOSuggestView, MultiDomainStatsView, WeeklyDigestView,
    WordPressDiscoverView, WordPressConnectView,
    ShopifyDiscoverView, ShopifyConnectView,
    WebflowDiscoverView, WebflowCollectionsView, WebflowConnectView,
    BillingMeView, BillingCheckoutView, BillingPortalView, BillingWebhookView,
    PlagiarismCheckView,
    PageSpeedView, LinkSuggestionsView, BacklinksView, SEOSchemaView,
    PublicSiteView, PublicSiteByDomainView, PublicPostsView, PublicPostDetailView,
    PublicTranslationsView, PublicCategoriesView,
    GSCOAuthUrlView, GSCOAuthCallbackView, GSCQueriesView,
)
from .api_v1 import (
    V1MeView, V1SitesView, V1ArticlesView, V1GenerateView,
    V1AuditView, V1BriefView, V1KeywordsView, V1RankSnapshotView,
    V1DigestView, TokenManagementView, TokenRevokeView,
)

router = DefaultRouter()
router.register(r'sites', SiteViewSet, basename='site')

urlpatterns = [
    path('auth/me/', UserProfileView.as_view(), name='user-profile'),
    path('sites/<int:site_id>/posts/', SitePostsView.as_view(), name='site-posts'),
    path('sites/<int:site_id>/posts/<slug:slug>/', SitePostDetailView.as_view(), name='site-post-detail'),
    path('sites/<int:site_id>/stats/', SiteStatsView.as_view(), name='site-stats'),
    path('sites/<int:site_id>/categories/', SiteCategoriesView.as_view(), name='site-categories'),
    path('sites/<int:site_id>/tags/', SiteTagsView.as_view(), name='site-tags'),
    path('sites/<int:site_id>/cannibalization/', SiteCannibalizationView.as_view(), name='site-cannibalization'),
    path('sites/<int:site_id>/audit-all/', BulkSEOAuditView.as_view(), name='site-audit-all'),
    path('sites/<int:site_id>/keywords/', TrackedKeywordsView.as_view(), name='site-keywords'),
    path('sites/<int:site_id>/keywords/<int:pk>/', TrackedKeywordDetailView.as_view(), name='site-keyword-detail'),
    path('sites/<int:site_id>/rank-snapshot/', RankSnapshotView.as_view(), name='site-rank-snapshot'),
    path('sites/<int:site_id>/rank-history/', RankHistoryView.as_view(), name='site-rank-history'),
    path('sites/<int:site_id>/content-decay/', ContentDecayView.as_view(), name='site-content-decay'),
    path('sites/<int:site_id>/topic-clusters/', TopicClusterView.as_view(), name='site-topic-clusters'),
    path('sites/<int:site_id>/link-graph/', LinkGraphView.as_view(), name='site-link-graph'),
    path('readability/', ReadabilityView.as_view(), name='readability'),
    path('sites/<int:site_id>/redirects/', RedirectsView.as_view(), name='site-redirects'),
    path('sites/<int:site_id>/redirects/<int:pk>/', RedirectDetailView.as_view(), name='site-redirect-detail'),
    path('sites/<int:site_id>/broken-links/', BrokenLinksView.as_view(), name='site-broken-links'),
    path('community-questions/', CommunityQuestionsView.as_view(), name='community-questions'),
    path('lexicon-check/', LexiconCheckView.as_view(), name='lexicon-check'),
    path('sites/<int:site_id>/local-business-schema/', LocalBusinessSchemaView.as_view(), name='site-local-business-schema'),
    path('sites/<int:site_id>/person-schema/', PersonSchemaView.as_view(), name='site-person-schema'),
    path('trends/', SearchTrendsView.as_view(), name='search-trends'),
    path('image-suggest/', ImageSEOSuggestView.as_view(), name='image-suggest'),
    path('multi-domain-stats/', MultiDomainStatsView.as_view(), name='multi-domain-stats'),
    path('sites/<int:site_id>/weekly-digest/', WeeklyDigestView.as_view(), name='site-weekly-digest'),
    path('wp/discover/', WordPressDiscoverView.as_view(), name='wp-discover'),
    path('wp/connect/', WordPressConnectView.as_view(), name='wp-connect'),
    path('shopify/discover/', ShopifyDiscoverView.as_view(), name='shopify-discover'),
    path('shopify/connect/', ShopifyConnectView.as_view(), name='shopify-connect'),
    path('webflow/discover/', WebflowDiscoverView.as_view(), name='webflow-discover'),
    path('webflow/collections/', WebflowCollectionsView.as_view(), name='webflow-collections'),
    path('webflow/connect/', WebflowConnectView.as_view(), name='webflow-connect'),
    path('billing/me/', BillingMeView.as_view(), name='billing-me'),
    path('billing/checkout/', BillingCheckoutView.as_view(), name='billing-checkout'),
    path('billing/portal/', BillingPortalView.as_view(), name='billing-portal'),
    path('billing/webhook/', BillingWebhookView.as_view(), name='billing-webhook'),
    path('plagiarism-check/', PlagiarismCheckView.as_view(), name='plagiarism-check'),
    path('sites/<int:site_id>/generate/', GenerateArticleView.as_view(), name='site-generate-article'),
    path('sites/<int:site_id>/generate-inline/', GenerateInlineView.as_view(), name='site-generate-inline'),
    path('sites/<int:site_id>/link-suggestions/', LinkSuggestionsView.as_view(), name='site-link-suggestions'),
    path('pexels/search/', PexelsSearchView.as_view(), name='pexels-search'),
    path('serper/images/', SerperImageSearchView.as_view(), name='serper-images'),
    path('generate-image/', GenerateImageView.as_view(), name='generate-image'),
    path('upload-image/', UploadImageView.as_view(), name='upload-image'),
    path('images/<uuid:uid>/', ServeImageView.as_view(), name='serve-image'),
    path('generate-tags/', GenerateTagsView.as_view(), name='generate-tags'),
    path('translate/', TranslatePostView.as_view(), name='translate-post'),
    path('seo-audit/', SEOAuditView.as_view(), name='seo-audit'),
    path('seo-fix/', SEOFixView.as_view(), name='seo-fix'),
    path('seo-suggest/', SEOSuggestView.as_view(), name='seo-suggest'),
    path('seo-synonyms/', SEOSynonymsView.as_view(), name='seo-synonyms'),
    path('seo-cache/clear/', SEOCacheClearView.as_view(), name='seo-cache-clear'),
    path('competitors/', CompetitorAnalysisView.as_view(), name='competitors'),
    path('keyword-research/', KeywordResearchView.as_view(), name='keyword-research'),
    path('content-brief/', ContentBriefView.as_view(), name='content-brief'),
    path('paa/', PAAView.as_view(), name='paa'),
    path('hreflang-check/', HreflangCheckView.as_view(), name='hreflang-check'),
    path('page-speed/', PageSpeedView.as_view(), name='page-speed'),
    path('backlinks/', BacklinksView.as_view(), name='backlinks'),
    path('seo-schema/', SEOSchemaView.as_view(), name='seo-schema'),
    # Google Search Console integration
    path('sites/<int:site_id>/gsc/oauth-url/', GSCOAuthUrlView.as_view(), name='gsc-oauth-url'),
    path('sites/<int:site_id>/gsc/oauth-callback/', GSCOAuthCallbackView.as_view(), name='gsc-oauth-callback'),
    path('sites/<int:site_id>/gsc/queries/', GSCQueriesView.as_view(), name='gsc-queries'),
    # Public API — for site frontends
    path('public/site-by-domain/', PublicSiteByDomainView.as_view(), name='public-site-by-domain'),
    path('public/sites/<int:site_id>/', PublicSiteView.as_view(), name='public-site'),
    path('public/sites/<int:site_id>/posts/', PublicPostsView.as_view(), name='public-posts'),
    path('public/sites/<int:site_id>/posts/<slug:slug>/', PublicPostDetailView.as_view(), name='public-post-detail'),
    path('public/sites/<int:site_id>/posts/<slug:slug>/translations/', PublicTranslationsView.as_view(), name='public-translations'),
    path('public/sites/<int:site_id>/categories/', PublicCategoriesView.as_view(), name='public-categories'),
    # Public developer API v1 (Bearer ApiToken auth)
    path('v1/me/', V1MeView.as_view(), name='v1-me'),
    path('v1/sites/', V1SitesView.as_view(), name='v1-sites'),
    path('v1/sites/<int:site_id>/articles/', V1ArticlesView.as_view(), name='v1-articles'),
    path('v1/sites/<int:site_id>/generate/', V1GenerateView.as_view(), name='v1-generate'),
    path('v1/audit/', V1AuditView.as_view(), name='v1-audit'),
    path('v1/brief/', V1BriefView.as_view(), name='v1-brief'),
    path('v1/sites/<int:site_id>/keywords/', V1KeywordsView.as_view(), name='v1-keywords'),
    path('v1/sites/<int:site_id>/keywords/snapshot/', V1RankSnapshotView.as_view(), name='v1-rank-snapshot'),
    path('v1/sites/<int:site_id>/digest/weekly/', V1DigestView.as_view(), name='v1-digest'),
    # Account-level token management (JWT auth)
    path('account/api-tokens/', TokenManagementView.as_view(), name='api-tokens'),
    path('account/api-tokens/<int:pk>/', TokenRevokeView.as_view(), name='api-token-revoke'),
    path('', include(router.urls)),
]
